export type DogSize = "small" | "medium" | "large" | "xlarge";

export const SIZE_LABELS: Record<DogSize, string> = {
  small: "Small",
  medium: "Medium",
  large: "Large",
  xlarge: "Extra large",
};

export const BREEDS_BY_SIZE: Record<DogSize, string[]> = {
  small: [
    "Affenpinscher",
    "Australian Terrier",
    "Bichon Frise",
    "Bolognese",
    "Border Terrier",
    "Boston Terrier",
    "Brussels Griffon",
    "Cairn Terrier",
    "Cavalier King Charles Spaniel",
    "Cavapoo",
    "Chihuahua",
    "Chinese Crested",
    "Coton de Tulear",
    "Dachshund (Miniature)",
    "Dandie Dinmont Terrier",
    "English Toy Terrier",
    "Fox Terrier (Toy)",
    "Havanese",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Jackapoo",
    "Japanese Chin",
    "King Charles Spaniel",
    "Lakeland Terrier",
    "Lhasa Apso",
    "Lowchen",
    "Maltese",
    "Maltipoo",
    "Manchester Terrier (Toy)",
    "Miniature Pinscher",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Papillon",
    "Pekingese",
    "Pomeranian",
    "Pomsky",
    "Poodle (Toy)",
    "Pug",
    "Puggle",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Shih Tzu",
    "Shih-poo",
    "Shihpoo",
    "Silky Terrier",
    "Skye Terrier",
    "Smooth Fox Terrier",
    "Tibetan Spaniel",
    "West Highland White Terrier",
    "Wire Fox Terrier",
    "Yorkiepoo",
    "Yorkipoo",
    "Yorkshire Terrier",
    "Other (small)",
  ],
  medium: [
    "American Cocker Spaniel",
    "Basenji",
    "Beagle",
    "Bedlington Terrier",
    "Brittany Spaniel",
    "Bull Terrier (Miniature)",
    "Clumber Spaniel",
    "Cockapoo",
    "Cocker Spaniel (English)",
    "Cockerpoo",
    "Collie (Smooth)",
    "Dachshund (Standard)",
    "English Springer Spaniel",
    "Field Spaniel",
    "Finnish Spitz",
    "French Bulldog",
    "Goldendoodle",
    "Harrier",
    "Hungarian Vizsla",
    "Irish Terrier",
    "Kerry Blue Terrier",
    "Keeshond",
    "Labradoodle",
    "Lagotto Romagnolo",
    "Lancashire Heeler",
    "Lurcher",
    "Portuguese Water Dog",
    "Poodle (Miniature)",
    "Schnauzer (Miniature)",
    "Schnoodle",
    "Shetland Sheepdog",
    "Soft Coated Wheaten Terrier",
    "Spaniel (Sussex)",
    "Spaniel (Welsh Springer)",
    "Spanish Water Dog",
    "Sproodle",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Tibetan Terrier",
    "Whippet",
    "Welsh Corgi (Cardigan)",
    "Welsh Corgi (Pembroke)",
    "Welsh Terrier",
    "Xoloitzcuintli",
    "Other (medium)",
  ],
  large: [
    "Afghan Hound",
    "Airedale Terrier",
    "Alaskan Malamute",
    "Belgian Malinois",
    "Belgian Shepherd (Groenendael)",
    "Belgian Shepherd (Tervuren)",
    "Border Collie",
    "Bouvier des Flandres",
    "Boxer",
    "Briard",
    "Chesapeake Bay Retriever",
    "Chow Chow",
    "Collie (Rough)",
    "Dalmatian",
    "Dobermann",
    "English Setter",
    "Flat Coated Retriever",
    "German Shepherd Dog",
    "German Shorthaired Pointer",
    "German Wirehaired Pointer",
    "Golden Retriever",
    "Gordon Setter",
    "Hungarian Wirehaired Vizsla",
    "Irish Red and White Setter",
    "Irish Setter",
    "Irish Water Spaniel",
    "Labradoodle (Standard)",
    "Labrador Retriever",
    "Large Munsterlander",
    "Norwegian Elkhound",
    "Nova Scotia Duck Tolling Retriever",
    "Old English Sheepdog",
    "Pharaoh Hound",
    "Pointer",
    "Poodle (Standard)",
    "Rhodesian Ridgeback",
    "Samoyed",
    "Siberian Husky",
    "Weimaraner",
    "Wetterhoun",
    "Other (large)",
  ],
  xlarge: [
    "Anatolian Shepherd Dog",
    "Bernese Mountain Dog",
    "Black Russian Terrier",
    "Bloodhound",
    "Boerboel",
    "Borzoi",
    "Bullmastiff",
    "Caucasian Shepherd Dog",
    "Cane Corso",
    "Dogue de Bordeaux",
    "English Mastiff",
    "Giant Schnauzer",
    "Great Dane",
    "Great Pyrenees",
    "Greater Swiss Mountain Dog",
    "Greyhound",
    "Irish Wolfhound",
    "Kangal Shepherd Dog",
    "Komondor",
    "Kuvasz",
    "Landseer",
    "Leonberger",
    "Neapolitan Mastiff",
    "Newfoundland",
    "Polish Lowland Sheepdog",
    "Pyrenean Mastiff",
    "Pyrenean Mountain Dog",
    "Rottweiler",
    "Saint Bernard",
    "Scottish Deerhound",
    "Spanish Mastiff",
    "Tibetan Mastiff",
    "Tosa Inu",
    "Other (extra large)",
  ],
};

// Build breed -> size lookup programmatically from BREEDS_BY_SIZE
export const BREED_TO_SIZE: Record<string, DogSize> = Object.entries(BREEDS_BY_SIZE).reduce(
  (acc, [size, breeds]) => {
    for (const breed of breeds) {
      acc[breed] = size as DogSize;
    }
    return acc;
  },
  {} as Record<string, DogSize>
);

// Flat list of all breeds with their sizes — handy for a combined dropdown
export const ALL_BREEDS_FLAT: { name: string; size: DogSize }[] = (
  Object.entries(BREEDS_BY_SIZE) as [DogSize, string[]][]
).flatMap(([size, breeds]) => breeds.map((name) => ({ name, size })));
